
server:
  port:8080

build:
  version: "3.0"

accounts:
  message: "Welcome to Accounts related prod APIs "
  contactDetails:
    name: "Test - Product Owner"
    email: "test@dev.com"
  onCallSupport:
    - (645) 395-4321
    - (213) 323-0484