spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s

      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  config:
    import: optional:configserver:http://localhost:8071/


jwt:
  public-key-uri: http://localhost:8075/api/auth/public-key

server:
  port: 8072

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    com:
      spring:
        microservice: debug
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"




info:
  app:
    name: gateway-server
    description: Gateway Service
    version: 1.0.0
  build:
    version: 1.0.0
    time: 2021-07-01T12:00:00Z

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
#        slow-call-rate-threshold: 50
#        slow-call-duration-threshold: 500
    instances:
      accountsCircuitBreaker:
        baseConfig: default
        waitDurationInOpenState: 5000
#        slow-call-rate-threshold: 10
#        slow-call-duration-threshold: 500

  timelimiter:
    configs:
        default:
            timeoutDuration: 5000
        accountsTimeLimiter:
            timeoutDuration: 5000
