spring:
  application:
    name: cards
  config:
    import: optional:configserver:http://localhost:8071/

server:
  port: 9000


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: cards
    description: Cards Service
    version: 1.0.0
  build:
    version: 1.0.0
    time: 2021-07-01T12:00:00Z

logging:
  level:
    com:
      spring:
        microservice: debug
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
